#
#  playground
#  Enhydra Application Makefile
#
#

#
#  Where is the root of the source tree?
#
ROOT =	../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = playground/presentation/media

JAR_INSTALL = \
	and.gif	\
	andACTIVE.gif \
	andPRESS.gif \
	not.gif \
	notACTIVE.gif \
	notPRESS.gif \
	or.gif \
	orACTIVE.gif \
	orPRESS.gif \
	logo.gif

include $(ROOT)/config.mk



