#!/usr/local/bin/tcsh
# $Id: updateHP,v 1.4 2000/04/27 08:03:21 locher Exp $

echo Update PSE Homepage...
cd /home/pse4/public_html
/usr/local/bin/cvs update
cd /tmp
/usr/local/bin/cvs co playground2/playground/presentation/Storyboard
cp -R playground2/playground/presentation/Storyboard /home/pse4/public_html/
cd /home/pse4/public_html
chmod -R 775 *
rm -rf storyboard/
mv Storyboard storyboard

