#!/usr/local/bin/tcsh
# $Id: updateHP,v 1.5 2000/05/08 06:23:10 locher Exp $

echo Update PSE Homepage...
cd /home/pse4/public_html
/usr/local/bin/cvs update

cd /tmp
/usr/local/bin/cvs co pse/kg2k/src/jobmatch/jobmatch/presentation/html
cp -R pse/kg2k/src/jobmatch/jobmatch/presentation/html /home/pse4/public_html/
cd /home/pse4/public_html
chmod -R 775 *
rm -rf storyboard/
mv html storyboard

