#
#  playground
#  Enhydra Application Makefile
#
#

#
#  Where is the root of the source tree?
#
ROOT =	../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = playground/business/tree

CLASSES =  \
	Tree \
	TreeNode \
	AbstractNode \
	ElementaryNode \
	BooleanNode \
	OperationNode \
	NOTNode \
	ANDNode \
	ORNode

include $(ROOT)/config.mk

