#
#  playground
#  Enhydra Application Makefile
#
#

#
#  Where is the root of the source tree?
#
ROOT =	../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = playground/presentation/media

JAR_INSTALL = Enhydra.gif

include $(ROOT)/config.mk



