#
#  jobmatch
#  Enhydra Application Makefile
#
#

SUBDIRS = \
	provider \
	candidate \
	company \
	service

#
#  Where is the root of the source tree?
#
ROOT =	../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = jobmatch/business

CLASSES =

USEICONTRACT=1

include $(ROOT)/config.mk

