#
#  jobmatch
#  Enhydra Application Makefile
#
#



SUBDIRS = \
	cv
#
#  Where is the root of the source tree?
#
ROOT =	../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = jobmatch/business/candidate

CLASSES = Candidate

USEICONTRACT=1

include $(ROOT)/config.mk

