#!/usr/local/bin/tcsh

# $Id: genJavadoc,v 1.3 2000/05/10 16:40:22 locher Exp $

set SOURCE = pse/kg2k/src/jobmatch/
set INDIR = /tmp/$SOURCE
set OUTDIR = /home/pse4/scr/public_html/javadoc
set CONTENTFILE = $INDIR/javadocFiles

set PARAMS = "-package -splitindex -use"
set HEADER = "<b>PSE 2000 Group 4</b>"

cd /tmp
/usr/local/bin/cvs co $SOURCE
mkdir -p $OUTDIR
cd $INDIR
/usr/local/jdk1.2.2/bin/javadoc $PARAMS -header "$HEADER" -sourcepath $INDIR -d $OUTDIR @$CONTENTFILE
