#!/usr/local/bin/tcsh

# $Id: genJavadoc,v 1.6 2000/05/10 18:31:36 locher Exp $

set SOURCE = pse/kg2k/src/jobmatch/
set INDIR = /tmp/$SOURCE
set OUTDIR = /home/pse4/public_html/doc
set CONTENTFILE = $INDIR/javadocFiles

set PARAMS = "-package -splitindex -use"
set HEADER = "<b>PSE 2000 Group 4</b>"

cd /tmp
/usr/local/bin/cvs -d /home/pse4/cvsroot co $SOURCE
mkdir -p $OUTDIR
cd $INDIR
/usr/local/jdk1.2.2/bin/javadoc $PARAMS -header "$HEADER" -sourcepath $INDIR -d $OUTDIR @$CONTENTFILE
chmod -R 775 $OUTDIR/* $OUTDIR