#!/usr/local/bin/tcsh

# $Id: launchPrototype,v 1.5 2000/04/13 13:59:51 locher Exp $
# make sure the prototype is running on vasarely.unibe.ch:9500
# with the following crontab entry on vasarely.unibe.ch
# 22,52 * * * * csh -c "nice /home/pse4/jobs/launchPrototype >& /home/pse4/jobs/protolaunch.txt"

if ( $CVSROOT ) then
    echo variables set
endif
source ~/.login 

echo Running protolaunch on
/usr/bin/uname -a
/usr/bin/date
echo " "

# Rebuild it
cd /home/pse4/scr
cvs co playground
cd playground
make

# Run it
cd /home/pse4/jobs
./runProto






