#!/usr/local/bin/tcsh

# $Id: quarterJobs,v 1.6 2000/04/12 21:01:36 locher Exp $
# these commands are run every 15 minutes with the following crontab entry on giger.unibe.ch
# 0,15,30,45 * * * * csh -c "/home/pse4/quarterJobs >& /home/pse4/jobs/quarterLog.txt"

echo Running quarter jobs on
/usr/bin/uname -a
/usr/bin/date
echo

cd /home/pse4/jobs
../updateHP
./genCL

