#!/usr/local/bin/tcsh

# $Id: runProto,v 1.4 2000/05/10 17:51:24 locher Exp $
# make sure the prototype is running on vasarely.unibe.ch:9500
# with the following crontab entry on vasarely.unibe.ch
# 22,52 * * * * csh -c "nice /home/pse4/jobs/launchPrototype >& /home/pse4/jobs/protolaunch.txt"

cd /home/pse4/scr/pse/kg2k/src/jobmatch/output

if (-e /tmp/protoALIVE) then 
    rm /tmp/protoALIVE 
endif

set PIDFILE=/home/pse4/jobs/`uname -n`PROTO.pid
echo $PIDFILE

if (-s $PIDFILE) then
    set OP=`cat $PIDFILE`
    echo $OP
    ls -1 /proc | grep "^$OP" > /tmp/protoALIVE
endif

if (-s /tmp/protoALIVE) then
    kill -KILL $OP
    echo Killing old process $OP ...
    sleep 5
endif

nohup start &
