#
#  jobmatch
#  Enhydra Application Makefile
#
#



SUBDIRS = \
	account

#
#  Where is the root of the source tree?
#
ROOT =	../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = jobmatch/business/provider

CLASSES =

include $(ROOT)/config.mk

