#
#  jobmatch
#  Enhydra Application Makefile
#
#

POST_SUBDIRS =\
	test

#
#  Where is the root of the source tree?
#
ROOT =	../../../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = jobmatch/business/company/profile/tree

CLASSES = \
	MatchTree \
	TreeNode \
	AbstractNode \
	MemoryNode \
	LeafSupport \
	OperationNode \
	ORNode \
	ANDNode \
	NOTNode

USEICONTRACT=1

include $(ROOT)/config.mk

