#
#  jobmatch
#  Enhydra Application Makefile
#
#

#
#  Where is the root of the source tree?
#
ROOT =	../../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = jobmatch/business/provider/account

CLASSES = \
	Account \
	CandidateAccount \
	AccountManager

include $(ROOT)/config.mk

