#
#  jobmatch
#  Enhydra Application Makefile
#
#

POST_SUBDIRS = test

#
#  Where is the root of the source tree?
#
ROOT =	../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = jobmatch/business/service

CLASSES = \
	MailMessage \
	Matcher \
	Mailer

USEICONTRACT=1

include $(ROOT)/config.mk

