#
#  jobmatch
#  Enhydra Application Makefile
#
#



SUBDIRS =

#
#  Where is the root of the source tree?
#
ROOT =	../../../../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = jobmatch/business/company/profile/tree/test

CLASSES = TestTree

include $(ROOT)/config.mk

