#
#  jobmatch
#  Enhydra Application Makefile
#
#

#
#  Where is the root of the source tree?
#
ROOT =	../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = jobmatch/business/entity

POST_SUBDIRS = \
	test

CLASSES = \
	Description \
	School \
	Schooltype \
	Graduation \
	Country \
	Address \
	EntityManager \
	Employer \
	Capability \
	Software \
	Programming \
	OperatingSystem \
	Language \
	Association

USEICONTRACT=1

include $(ROOT)/config.mk

