#
#  jobmatch
#  Enhydra Application Makefile
#
#

#
#  Where is the root of the source tree?
#
ROOT =	../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = jobmatch/business/entity

CLASSES = \
	Description \
	School \
	Schooltype \
	Graduation \
	Country \
	EntityManager

USEICONTRACT=1

include $(ROOT)/config.mk

