#
#  jobmatch
#  Enhydra Application Makefile
#
#

#
#  Where is the root of the source tree?
#
ROOT =	../../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = jobmatch/business/candidate/cv

CLASSES = \
	Formation \
	CVSection

USEICONTRACT=1

include $(ROOT)/config.mk

