#
#  jobmatch
#  Enhydra Application Makefile
#
#

#
#  Where is the root of the source tree?
#
ROOT =	../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = jobmatch/presentation/test


#
# To add more Java classes, create the .java files and add their names to
# this list (without the .java extension).
#
CLASSES = UnitTests


HTML_DIR = .
HTML_CLASSES = \
	TestResultHTML

include $(ROOT)/config.mk

