#
#  jobmatch
#  Enhydra Application Makefile
#
#



SUBDIRS = \
	tree

#
#  Where is the root of the source tree?
#
ROOT =	../../../..

#
#  What package does this directory represent? (use / instead of .)
#
PACKAGEDIR = jobmatch/business/company/profile

CLASSES =

USEICONTRACT=1

include $(ROOT)/config.mk

